spring:
    application:
        name: greeting-service

greeting-service:
    greeting: "Olá"
    default-value: "Test"

management:
    endpoints:
        web:
            exposure:
                include: '*'